services:
  flask_ui:
    build:
      context: ./flask_ui
    container_name: flask_ui
    ports:
      - 5005:5005
    volumes:
      - ./flask_ui:/app

  vite_lit_component:
    build: ./vite_lit_component
    container_name: vite_lit_component
    volumes:
      - ./flask_ui/static/components:/dist
      - ./flask_ui/templates:/templates
      - ./flask_ui/static:/static
      - ./vite_lit_component/src:/src
      - ./vite_lit_component/index.html:/index.html