services:
  nuxt-ts-tailwind:
    build:
      context: ./nuxt-ts-tailwind
      dockerfile: dockerfile-stage
    container_name: nuxt-ts-tailwind
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - DB_API_BASE_URL=${DB_API_BASE_URL}