FROM python:3.12.3-slim

RUN apt-get update -y
RUN apt-get install -y build-essential
RUN apt-get install -y libpq-dev
RUN apt install python3-pydot graphviz -y

RUN pip install --upgrade pip
RUN pip install jupyterlab

CMD ["jupyter", "lab", "--ip=0.0.0.0", "--no-browser", "--allow-root", "--notebook-dir=/src"]