services:
  pgsql:
    image: postgres:13
    container_name: pgsql
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data/production:/var/lib/postgresql/data/pgdata
    env_file:
      - ./env/.env.production
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
