services:
  pgsql:
    image: postgres:12
    container_name: pgsql
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data/stage:/var/lib/postgresql/data/pgdata
    env_file:
      - ./env/.env.stage
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata