apiVersion: apps/v1
kind: Deployment
metadata:
  name: piggyflow-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: piggyflow
  template:
    metadata:
      labels:
        app: piggyflow
    spec:
      containers:
        - name: django-ninja-api
          image: piggyflow-django-ninja-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_SERVER
              value: "piggyflow-pgsql-service"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "app"
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "admin"
            - name: DJANGO_DEBUG
              value: "False"
            - name: DJANGO_DEPLOY
              value: "production"
          command:
            - "sh"
            - "-c"
            - "python manage.py makemigrations && python manage.py migrate && python main.py"
        - name: pgsql
          image: postgres:13
          ports:
            - name: pgsql-port
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "app"
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "admin"
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
        - name: redis
          image: redis:6
          ports:
            - containerPort: 6379
      volumes:
        - name: postgres-storage
          hostPath:
            path: /k8s/piggyflow/production
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: piggyflow-django-ninja-api-service
spec:
  type: NodePort
  selector:
    app: piggyflow
  ports:
    - protocol: TCP
      name: django-ninja-api
      port: 8000
      targetPort: 8000
      nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: piggyflow-pgsql-service
spec:
  selector:
    app: piggyflow
  ports:
    - protocol: TCP
      name: pgsql
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: piggyflow-redis-service
spec:
  selector:
    app: piggyflow
  ports:
    - protocol: TCP
      name: redis
      port: 6379
      targetPort: 6379
