services:
  django-ninja-api:
    build:
      context: .
      args:
        - BASE_IMAGE_VERSION=${BASE_IMAGE_VERSION}
      dockerfile: ./docker/dockerfile-stage
    container_name: django-ninja-api-${DJANGO_DEPLOY}
    restart: always
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}
    volumes:
      - ./django-ninja-api:/app
    env_file:
      - ./env/.env.stage
    depends_on:
      - pgsql
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python main.py"
