FROM ansoncar/django-ninja-api-basis:v0.7.0

WORKDIR /app
COPY ./django-ninja-api .

# api tool
RUN apt-get install -y opencc
RUN pip install opencc
RUN pip install hyper
RUN pip install googletrans==4.0.0-rc1