ARG BASE_IMAGE_VERSION
FROM ansoncar/django-ninja-api-basis:${BASE_IMAGE_VERSION}

WORKDIR /app
COPY ./django-ninja-api .

# api tool
RUN apt-get install -y opencc
RUN pip install opencc hyper googletrans==4.0.0-rc1