services:
  nuxt-ts-tailwind:
    build:
      context: .
      dockerfile: ./docker/dockerfile
    container_name: nuxt-ts-tailwind
    ports:
      - 3000:3000
    volumes:
      - ./pages:/app/pages
      - ./assets:/app/assets
      - ./utils:/app/utils
      - ./server:/app/server
      - ./components:/app/components
      - ./layouts:/app/layouts
      - ./middleware:/app/middleware
      - ./plugins:/app/plugins
    env_file:
      - ./env/.env.local