services:
  db_api_ninja:
    build:
      context: ./db_api_ninja
      dockerfile: ./docker/dockerfile-stage
    container_name: db_api_ninja
    restart: always
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}
    volumes:
      - ./db_api_ninja:/app
    env_file:
      - ./env/.env.stage
    depends_on:
      - pgsql
    command: sh -c "python manage.py migrate && python main.py"