FROM python:3.10.12-slim

WORKDIR /app
COPY . .

# RUN apt-get install build-dep python-psycopg2

RUN apt update
RUN apt-get update -y
RUN apt-get install -y opencc

RUN pip install --upgrade pip

RUN pip install opencc
RUN pip install hyper
RUN pip install googletrans==4.0.0-rc1

RUN pip install Django==4.2.7
RUN pip install django-ninja
RUN pip install django-ninja-jwt

RUN pip install django-cors-headers

RUN pip install psycopg2-binary
RUN pip install python-dotenv
RUN pip install uvicorn

# RUN python manage.py makemigrations
# RUN python manage.py migrate

CMD [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
# CMD ["python", "main.py"]