name: build website
run-name: build website
on:
  push:
    branches:
      - 'main'

jobs:
  build-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: docker compose
        working-directory: frontend
        run: docker compose -f docker-compose.product.yml up -d --build --force-recreate &&
             docker system prune -af
